### PR TITLE
intro / it-academy / JC1-117-22 / Victor Polonnikov / Done tasks 1-2

### PR DESCRIPTION
**Pull request by VictPol**
## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

### CODE REVIEW

**Comment by VictPol** [comment]
Add 2 files with home tasks for intro

**Comment by VictPol** [comment]
fix name of PR

**Comment by VictPol** [comment]
fix name of PR

**Review by rakovets — APPROVED** [review]
Approved

**Pull request closed without merging**
